### ISSUE TITLE
Inconsistent results between micromatch & isMatch if input string is identical to a pattern

### ISSUE THREAD

**Issue by Jerska** [micromatch/micromatch#144]
Hi and thanks for this awesome library!
Here's a small inconsistency we noticed.

## Please describe the **minimum necessary steps** to reproduce this issue:

```js
require('micromatch')(['!*.js'], '!*.js').length > 0 // => true
```

With `isMatch`, it gives back the expected result:

```js
require('micromatch').isMatch('!*.js', '!*.js') // => false
```

Also, if the string is not exactly the same one as the excluded pattern, it works:

```js
require('micromatch')(['!**.js'], '!*.js').length > 0 // => false
```

## What is happening (but shouldn't):

Anything suffixed by `.js` should be ignored, including strings starting with `!`.

## What should be happening instead?

It should return an empty array.

I believe this is due to the string comparison happening in https://github.com/micromatch/micromatch/blob/f2ce9d20c3ba9c0d141854a1dde470a42810f502/index.js#L108-L110

The same thing happens if you use brace expansion:

```js
require('micromatch')(['{abc,def}'], ['{abc,def}']).length > 0
```

**Comment by Jerska** [comment]
<details>
<summary>Removing the equality check breaks 4 tests:</summary>

```
  4 failing

  1) micromatch posix paths should match literal brackets:

      AssertionError [ERR_ASSERTION]: a [b] c
      + expected - actual

      -[]
      +[
      +  "a [b] c"
      +]
      
      at module.exports (test/support/match.js:20:10)
      at Context.<anonymous> (test/api.js:106:7)

  2) bash options and features: bash should use quoted characters as literals::

      AssertionError [ERR_ASSERTION]: \*
      + expected - actual

       [
         "*"
      +  "\\*"
       ]
      
      at module.exports (test/support/match.js:20:10)
      at Context.<anonymous> (test/bash.js:56:9)

  3) brackets .match should match literal brackets:

      AssertionError [ERR_ASSERTION]: a [b] c
      + expected - actual

      -[]
      +[
      +  "a [b] c"
      +]
      
      at module.exports (test/support/match.js:20:10)
      at Context.<anonymous> (test/brackets.js:51:7)

  4) options options.noext should not match extglobs when noext is true:

      AssertionError [ERR_ASSERTION]: a/!(z)
      + expected - actual

      -[]
      +[
      +  "a/!(z)"
      +]
      
      at module.exports (test/support/match.js:20:10)
      at Context.<anonymous> (test/options.js:155:7)
```
</details>

**Comment by jonschlinkert** [comment]
@Jerska thanks for the issue. I'll look into this and see what's happening.
