### ISSUE TITLE
SyntaxError: Invalid or unexpected token when running from Jest

### ISSUE THREAD

**Issue by Dizzienoo** [micromatch/micromatch#223]
_(Thanks for reporting an issue to micromatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then proceed to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:

Install Jest (latest version) and create any test and try to run.

…

## What is happening that shouldn't be?

Error returns:

G:\Users\Work\Documents\Gits\JestIssue\node_modules\micromatch\index.js:1
VW��
  

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)   
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (G:\Users\Work\Documents\Gits\JestIssue\node_modules\jest-haste-map\build\watchers\common.js:10:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
error Command failed with exit code 1.

…

## What should be happening instead?

Test should run.
…

This seems to be an issue with micromatch as when I copy the development copy from 4.0.3 into the node_modules folder the problem stops.

Repo example of the problem: 
https://github.com/Dizzienoo/JestIssue

**Comment by jonschlinkert** [comment]
Sorry for the late reply. What version of node.js are (were) you running? Does it happen with the latest version of node?
